/* This file is generated by the cgen program, https://github.com/morten-krogh/cgen. The cgen program is released under the MIT license.*/

#include <stddef.h>

struct vector_int {
       int *data;
       size_t size;
       size_t capacity;
};

struct vector_int *vector_int_init(struct vector_int *vec);
void vector_int_free(struct vector_int *vec);
struct vector_int *vector_int_set_capacity(struct vector_int *vec, size_t capacity);
struct vector_int *vector_int_append(struct vector_int *vec, int t);
