/* This file is generated by the cgen program, https://github.com/morten-krogh/cgen. The cgen program is released under the MIT license.*/

#include "vector_int.h"

#include <stdlib.h>
#include <stdio.h> // remove again

struct vector_int *vector_int_init(struct vector_int *vec)
{
	vec->data = NULL;
	vec->size = 0;
	vec->capacity = 0;

	return vec;
}

void vector_int_free(struct vector_int *vec)
{
	free(vec->data);
}

struct vector_int *vector_int_set_capacity(struct vector_int *vec, size_t capacity)
{
	int *data;
	if ((data = realloc(vec->data, capacity * sizeof vec->data)) != NULL) {
		vec->data = data;
		vec->capacity = capacity;
		if (vec->size > capacity) vec->size = capacity;
		printf("New capacity %zu\n", capacity);
	}

	return vec;
}

struct vector_int *vector_int_append(struct vector_int *vec, int t)
{
	if (vec->size == vec->capacity) {
		size_t new_capacity = 2 * vec->capacity + 1;
		vector_int_set_capacity(vec, new_capacity);
	}

	vec->data[vec->size] = t;
	vec->size++;
	
	return vec;
}
