/* This file is generated by the cgen program, https://github.com/morten-krogh/cgen. The cgen program is released under the MIT license.*/

#include <stddef.h>

struct vector_ul {
       unsigned long *data;
       size_t size;
       size_t capacity;
};

struct vector_ul *vector_ul_init(struct vector_ul *vec);
void vector_ul_free(struct vector_ul *vec);
struct vector_ul *vector_ul_set_capacity(struct vector_ul *vec, size_t capacity);
struct vector_ul *vector_ul_append(struct vector_ul *vec, unsigned long t);
