/* This file is generated by the cgen program, https://github.com/morten-krogh/cgen. The cgen program is released under the MIT license.*/

#include "vector_unsigned_long.h"

#include <stdlib.h>

struct vector_ul *vector_ul_init(struct vector_ul *vec)
{
	vec->data = NULL;
	vec->size = 0;
	vec->capacity = 0;

	return vec;
}

void vector_ul_free(struct vector_ul *vec)
{
	free(vec->data);
}

struct vector_ul *vector_ul_set_capacity(struct vector_ul *vec, size_t capacity)
{
	if ((unsigned long *data = realloc(vec->data, capacity)) != NULL) {
		vec->data = data;
		vec->capacity = capacity;
		if (vec->size > capacity) vec->size = capacity;
	}

	return vec;
}

struct vector_ul *vector_ul_append(struct vector_ul *vec, unsigned long t)
{
	if (vec->size == vec->capacity) {
		size_t new_capacity = 2 * vec->capacity + 1;
		vector_ul_set_capacity(vec, new_capacity);
	}

	vec->data[vec->size] = t;
	vec->size++;
	
	return vec;
}
