/* This file is generated by the cgen program, https://github.com/morten-krogh/cgen.
 * The cgen program is released undwer the MIT license.
*/

#include <stddef.h>

struct vector_int {
       int *data;
       size_t size;
       size_t capacity;
};



